version: 2
project_name: cosmosigner

env:
  - CGO_ENABLED=0

builds:
  - id: darwin
    main: ./cmd/cosmosigner
    binary: cosmosigner
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/voluzi/cosmosigner/internal/version.Version={{ .Version }}
      - -X github.com/voluzi/cosmosigner/internal/version.Commit={{ .Commit }}
      - -X github.com/voluzi/cosmosigner/internal/version.Date={{ .Date }}

  - id: linux
    main: ./cmd/cosmosigner
    binary: cosmosigner
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/voluzi/cosmosigner/internal/version.Version={{ .Version }}
      - -X github.com/voluzi/cosmosigner/internal/version.Commit={{ .Commit }}
      - -X github.com/voluzi/cosmosigner/internal/version.Date={{ .Date }}

universal_binaries:
  - id: darwin
